### PR TITLE
Remove deprecated mapTestClassNameToCoveredClassName

### PR DESCRIPTION
**Pull request by lambreva**
This option should be removed in order the tests to pass

### CODE REVIEW

**Comment by fjbender** [comment]
Thanks! Seems to work for 6.0 and 6.1, but 6.2 tests are broken (possibly due to a different reason): https://github.com/PAYONE-GmbH/oxid-6/pull/128/checks?check_run_id=340246590

**Comment by lambreva** [comment]
> Thanks! Seems to work for 6.0 and 6.1, but 6.2 tests are broken (possibly due to a different reason): https://github.com/PAYONE-GmbH/oxid-6/pull/128/checks?check_run_id=340246590

Hi, about the broken tests for 6.2 - We had similar issues on our CI in case testing_library b-6.x branch is used. Happens in case shop indeed gets built in one place and then is deployed to another directory.
Modules are installed at this point but not yet activated. Means we have entries for developer-tools in the generated_services.yaml but not yet for modules. Modules are not a problem as they get activated via testing_library and get the correct entries in the generated_services.yaml at the target position. Non-module services are removed if paths to services.yaml does not match in the target directory. Hence the 'missing service' message.
Please make sure to run composer update in case shop was moved.

**Comment by fjbender** [comment]
Doesn't seem to do the trick :( Added it right before running the tests: https://github.com/PAYONE-GmbH/oxid-6/blob/8e71d3bd41074c47fb2fa1b61d83c7e6ad1fc817/.github/workflows/main.yml#L61

**Comment by hkreuter** [comment]
If I see it correctly, tests are run on b-6.2-beta-ce. Might be better to try with the RC (b-6.2-rc-ce).
The change in this PR is not the cause why the checks fail for 6.2, as I see the master branch checks fail as well at the moment. Would be great if you could merge that PR anyway.
Please try to run the tests with the RC and then let's try to figure out how to fix the build if it still fails.

**Comment by fjbender** [comment]
Thanks, that did it :) I hadn't notived the rc was available. Will merge now.

**Pull request merged**
